version: '3.1'

services:
  app:
    image: mongo:latest
    container_name: docker-mongo-demo1
    restart: always
    build: .
    ports:
      - '5500:5500'
    external_links:
      - mongo_db

    environment:
      port: 5432
      USERNAME: root
      PASSWORD: root
      MONGODB_URL: mongodb+srv://admin:admin@cluster0.jppso.mongodb.net/?retryWrites=true&w=majority
      DB_NAME: my_db
      NAME: vaibhav
volumes:
 mongo_db: { }
