version: '3.1'

services:
  mongo_db:
    image: mongo:latest
    container_name: db_service
    restart: always
    volumes:
      - mongo_db:/data/db

    environment:
      port: 5432
      USERNAME: root
      PASSWORD: root
      MONGODB_URL: mongodb://db_service:27017/
      DB_NAME: my_db
      NAME: vaibhav
volumes:
 mongo_db: { }